version: '3.5'

services:

# -------------------- Monitoring + Alerts ----------------------- #

  prometheus:
    image: prom/prometheus:v2.11.1
    restart: always
    networks:
      - h3alth_web
    labels:
      - traefik.enable=false
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - alertmanager
      - cadvisor
      - grafana
    container_name: prometheus 

  node-exporter:
    image: prom/node-exporter:v0.18.0
    restart: always
    networks:
      - h3alth_web
    labels:
      - traefik.enable=false
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    container_name: node-exporter

  alertmanager:
    image: prom/alertmanager:v0.18.0
    restart: always
    networks:
      - h3alth_web
    labels:
      - traefik.enable=false
    volumes:
      - ./alertmanager/config.yml:/alertmanager/config.yml
      - ./alertmanager/notifications.tmpl:/alertmanager/notifications.tmpl
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    container_name: alertmanager

  cadvisor:
    image: google/cadvisor:v0.33.0
    restart: always
    networks:
      - h3alth_web
    labels:
      - traefik.enable=false
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  
    container_name: cadvisor

  grafana:
    image: grafana/grafana:5.4.2
    restart: always
    networks:
      - h3alth_web
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    labels:
      - traefik.frontend.rule=Host:${GRAFANA_DOMAIN}
      - traefik.port=3000
      - traefik.acme.domains=${GRAFANA_DOMAIN}
      - traefik.acme.domains=${GRAFANA_DOMAIN}
    volumes:
      - grafana-data:/var/lib/grafana
    container_name: grafana


# ---------------------- Volumes + Networks ------------------------- #

networks:
  h3alth_web:
    external: true

volumes:
  prometheus-data:
  alertmanager-data:
  grafana-data:
