FROM ubuntu:16.04

RUN apt-get update && apt-get install -y gettext-base curl jq

RUN apt-get install -y apt-transport-https ca-certificates software-properties-common
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
RUN  apt-get update && apt-get install -y docker-ce
RUN curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

RUN mkdir /coordinator
WORKDIR /coordinator
ENTRYPOINT ["bash", "/coordinator/crawl.sh"]